name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./restaurant-backend-nestjs
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/anawuma-backend:latest"

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./restaurant-frontend
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/anawuma-frontend:latest"
          build-args: |
            REACT_APP_API_URL=http://${{ secrets.HOST_IP }}:3000/api

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy docker-compose via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/root/anawuma"

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/anawuma
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "REACT_APP_API_URL=http://${{ secrets.HOST_IP }}:3000/api" >> .env
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose pull
            docker rm -f anawuma_frontend anawuma_backend anawuma_db || true
            docker-compose up -d
            docker image prune -f
